- name: Stop OpsCenter
  service:
    name: opscenterd
    state: stopped
  when: dse_install_type == 'package'


- name: Delete OpsCenter data directories
  file:
    path: "{{ item }}"
    state: absent
  when: dse_install_type == 'package'
  with_items:
    - "{{ opscenter_lib_directory }}"
    - "{{ opscenter_log_directory }}"
    - "{{ opscenter_run_files_directory }}"
    - "{{ opscenter_binary_files_directory }}"
    - "{{ opscenter_doc_directory }}"
    - "{{ opscenter_clusters_directory }}"
