# This play will stop all data nodes, agents, and delete their data directories
#
- hosts: opscenter
  remote_user: "{{creds.remote_user}}"
  become: true
  ignore_errors: yes
  roles:
  - opscenter-reset

- hosts: storeseeds,storenonseeds,DC1,DC2
  remote_user: "{{creds.remote_user}}"
  become: true
  ignore_errors: yes
  roles:
  - db-reset
