# Stop the agents, DSE, and delete the data directories

- name: Stop DataStax Agent
  service:
    name: datastax-agent
    state: stopped
  when: dse_install_type == 'package'


- name: Stop DSE
  service:
    name: dse
    state: stopped
  when: dse_install_type == 'package'


- name: Delete DSE and Agent data directories
  file:
    path: "{{ item }}"
    state: absent
  when: dse_install_type == 'package'
  with_items:
    - "{{ dse_hints_directory }}"
    - "{{ dse_data_file_directories }}"
    - "{{ dse_commitlog_directory }}"
    - "{{ dse_saved_caches_directory }}"
    - "{{ dse_solr_data_directory }}"
    - "{{ dse_agent_directory }}"
    - "{{ dse_agent_conf_directory }}"
    - "{{ dse_agent_log_directory }}"
    - "{{ dse_agent_backup_staging_directory }}"
    - "{{ dse_agent_backup_storage_directory }}"
    - "{{ dse_agent_tmp_directory }}"


  #shell: |
    #sudo service dse stop
  #args:
    #warn: false
