# Stop the agents, DSE, and delete the data directories

- name: Stop DataStax Agent
  service:
    name: datastax-agent
    state: stopped
  when: dse_install_type == 'package'


- name: Stop DSE
  service:
    name: dse
    state: stopped
  when: dse_install_type == 'package'


- name: Uninstall DataStax Enterprise
  yum:
    name: ["dse-full", "dse", "dse-libgraph","dse-libcassandra","dse-libhadoop2-client","dse-libsolr","dse-libtomcat","dse-liblog4j","dse-libspark"]
    enablerepo: datastax
    state: absent
  when: dse_install_via == 'online'


- name: Uninstall DataStax Agent
  yum:
    name: "datastax-agent"
    enablerepo: opscenter
    state: absent


- name: Delete DSE and Agent data directories
  file:
    path: "{{ item }}"
    state: absent
  when: dse_install_type == 'package'
  with_items:
    - "{{ cassandra_directory }}"
    - "{{ dse_conf_directory }}"
    - "{{ dse_solr_data_directory }}"
    - "{{ dse_agent_directory }}"
    - "{{ dse_agent_conf_directory }}"
    - "{{ dse_agent_log_directory }}"
    - "{{ dse_agent_backup_staging_directory }}"
    - "{{ dse_agent_backup_storage_directory }}"
    - "{{ dse_agent_tmp_directory }}"


  #shell: |
    #sudo service dse stop
  #args:
    #warn: false
