# Handlers for agent related notifications

- name: restart-agent
  service:
    name: datastax-agent
    state: restarted
  when: dse_install_type == 'package'


  #shell: |
    #sudo service datastax-agent restart
  #args:
    #warn: false
